[package]
name = "pest"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = { version = "0.92.2", features = ["clang-runtime"] }
serde-pickle = "1.1.1"
byteorder = "1.5.0"
serde = { version = "1.0.210", features = ["derive"] }
tflite = "0.9.8"
anyhow = "1.0.87"
